version: 2.1
executors:
  general-executor:
    docker:
      - image: circleci/ruby:2.4.1
  lw_executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"
  build_frontend:
    executor: lw_executor
    steps:
      - checkout
      - run:
          name: build Frontend
          command:  |  #specify the instructions to be executed while in this section. This should be modify accordingly
            cd frontend 
            npm install 
            #npm audit fix
            npm run build 
            
  build_backend:
    executor: lw_executor
    steps:
      - checkout
      - run:
          name: Backend build
          command: |
            cd backend
            npm install
            npm run build
  test_frontend:
    executor: lw_executor
    steps:
      - checkout
      - run: mkdir -p ~/junit
      - run:
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          command: |
            cd frontend
            npm install mocha-junit-reporter --save-dev
            mocha test --reporter mocha-junit-reporter
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit          
      - run: 
          name: test front end
          command: |
            cd frontend
            npm install
            npm run test
      #- run:
      #    name: Save test results
      #    command: |
      #      mkdir -p ~/cucumber
      #      bundle exec cucumber --format junit --out ~/cucumber/junit.xml
      #    when: always
      #- store_test_results:
      #    path: ~/cucumber
      #- store_artifacts:
      #    path: ~/cucumber
      ### THIS IS ANOTHER OPTION
            
  test_backend:
    executor: lw_executor
    steps:
      - checkout
      - run: mkdir -p ~/junit
      - run:
          command: |
            cd backend
            npm install mocha-junit-reporter --save-dev
      - run:
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          command: mocha test --reporter mocha-junit-reporter
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit  
      - run: 
          name: test front end
          command: |
            cd backend
            npm install
            npm run test

  check_vulnerabilities:
    executor: lw_executor
    steps:
      - checkout
      - run: 
          name: checking system vulnerabilities Frontend
          command: |
            cd frontend
            #npm install
            npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force
          when: on_fail
      - run:
          name: checking system vulnerabilities backend
          command: |
            cd backend
            #npm install
            npm audit --audit-level=critical
            npm audit fix --audit-level=critical --force
          when: on_fail


  

workflows: #workflows specify jobs to run
  default:
    jobs:
      - hello-world
      - build_frontend
      - build_backend
      - test_frontend:
          requires:
            - build_frontend
      - test_backend:
          requires:
            - build_backend
      - check_vulnerabilities:
          requires:
            - build_frontend
            - build_backend