version: 2.1
executors:
  general-executor:
    docker:
      - image: circleci/ruby:2.4.1
  lw_executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"
  build_frontend:
    executor: lw_executor
    steps:
      - checkout
      - run:
          name: build Frontend
          command:  |  #specify the instructions to be executed while in this section. This should be modify accordingly
            cd frontend 
            npm install 
            npm audit fix
            npm run build 
            
  build_backend:
    executor: lw_executor
    steps:
      - checkout
      - run:
          name: Backend build
          command: |
            cd backend
            npm install
            npm audit fix
            npm run build
  test_frontend:
    executor: lw_executor
    steps:
      - checkout
      - run: 
          name: test front end
          command: |
            cd frontend
            npm install
            npm audit fix
            npm run test
      - run:
        name: Save test results
        command: |
          mkdir -p ~/cucumber
          bundle exec cucumber --format junit --out ~/cucumber/junit.xml
        when: always
    - store_test_results:
        path: ~/cucumber
    - store_artifacts:
        path: ~/cucumber
      #- run: mkdir ~/junit
      #- run:
      #    command: mocha test --reporter mocha-junit-reporter
      #    environment:
      #      MOCHA_FILE: ~/junit/test-results.xml
      #    when: always
      #- store_test_results:
      #    path: ~/junit
      #- store_artifacts:
      #    path: ~/junit          

            

workflows: #workflows specify jobs to run
  default:
    jobs:
      - hello-world
      - build_frontend
      - build_backend
      - test_frontend
